version: "3"

services:
  postgres:
    image: postgres:15.1
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
